CREATE SEQUENCE IF NOT EXISTS questions_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS quiz_categories_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS quiz_rating_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS quizzes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS user_statistics_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE question_correct_answers
(
    question_id    BIGINT NOT NULL,
    correct_answer VARCHAR(255)
);

CREATE TABLE question_option_images
(
    question_id  BIGINT NOT NULL,
    option_image VARCHAR(255)
);

CREATE TABLE question_options
(
    question_id BIGINT NOT NULL,
    option_text VARCHAR(500)
);

CREATE TABLE questions
(
    case_sensitive      BOOLEAN,
    points              INTEGER,
    question_index      INTEGER,
    time_limit_seconds  INTEGER,
    id                  BIGINT        NOT NULL,
    quiz_id             BIGINT        NOT NULL,
    text                VARCHAR(1000) NOT NULL,
    correct_text_answer VARCHAR(255),
    image_url           VARCHAR(255),
    type                VARCHAR(255)  NOT NULL,
    CONSTRAINT questions_pkey PRIMARY KEY (id)
);

CREATE TABLE quiz_categories
(
    active      BOOLEAN NOT NULL,
    id          BIGINT  NOT NULL,
    color       VARCHAR(255),
    description VARCHAR(255),
    icon        VARCHAR(255),
    name        VARCHAR(255),
    CONSTRAINT quiz_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE quiz_rating
(
    rating     DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    id         BIGINT           NOT NULL,
    quiz_id    BIGINT           NOT NULL,
    user_id    BIGINT           NOT NULL,
    comment    VARCHAR(255),
    CONSTRAINT quiz_rating_pkey PRIMARY KEY (id)
);

CREATE TABLE quizzes
(
    average_rating     DOUBLE PRECISION,
    is_public          BOOLEAN,
    max_questions      INTEGER,
    plays_count        INTEGER,
    rating_counts      INTEGER,
    time_limit_minutes INTEGER,
    category_id        BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    creator_id         BIGINT                                  NOT NULL,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description        VARCHAR(500)                            NOT NULL,
    difficulty_level   VARCHAR(255)                            NOT NULL,
    head_image_url     VARCHAR(255),
    title              VARCHAR(255)                            NOT NULL,
    CONSTRAINT quizzes_pkey PRIMARY KEY (id)
);

CREATE TABLE user_friends
(
    friend_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT user_friends_pkey PRIMARY KEY (friend_id, user_id)
);

CREATE TABLE user_roles
(
    roles   SMALLINT,
    user_id BIGINT NOT NULL
);

CREATE TABLE user_statistics
(
    average_score                   INTEGER,
    best_score                      INTEGER,
    longest_win_streak              INTEGER,
    total_correct_answers           INTEGER,
    total_correct_questions_answers INTEGER,
    total_quizzes_created           INTEGER,
    total_quizzes_played            INTEGER,
    total_score                     INTEGER,
    win_streak                      INTEGER,
    id                              BIGINT NOT NULL,
    user_id                         BIGINT,
    CONSTRAINT user_statistics_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    is_public_profile     BOOLEAN NOT NULL,
    receive_notifications BOOLEAN NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    id                    BIGINT  NOT NULL,
    last_login_at         TIMESTAMP WITHOUT TIME ZONE,
    avatar_url            VARCHAR(255),
    biography             VARCHAR(255),
    email                 VARCHAR(255),
    name                  VARCHAR(255),
    password              VARCHAR(255),
    username              VARCHAR(255),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE user_statistics
    ADD CONSTRAINT user_statistics_user_id_key UNIQUE (user_id);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE user_friends
    ADD CONSTRAINT fk11y5boh1e7gh60rdqixyetv3x FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE question_correct_answers
    ADD CONSTRAINT fk20d694wynxtnrdqn8d6g1brcp FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE NO ACTION;

ALTER TABLE question_option_images
    ADD CONSTRAINT fk4lkf10bh2nrs9r5qrfeut15s5 FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE NO ACTION;

ALTER TABLE user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_friends
    ADD CONSTRAINT fkk08ugelrh9cea1oew3hgxryw2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE user_statistics
    ADD CONSTRAINT fkn3hnvsmybu7g7ntrwpg563sao FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE quiz_rating
    ADD CONSTRAINT fknm5swvamehmd43e7iotro15xp FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE question_options
    ADD CONSTRAINT fksb9v00wdrgc9qojtjkv7e1gkp FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE NO ACTION;